# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Generate ``docs/schema-reference.md`` from the recipe and cluster dataclasses.

The recipe schema is the dataclass tree rooted at :class:`SrtConfig`; the
cluster config (``srtslurm.yaml``) is :class:`ClusterConfig`. This module walks
both and renders one Markdown table per dataclass, so the field-level reference
cannot drift from the code: the checked-in file is regenerated by
``srtctl schema-docs`` and CI fails when it is stale.

Descriptions come from two places, in priority order: an ``Attributes:`` block
in the class docstring (Google style), then the ``#`` comment block directly
above a field or the trailing comment on its line.
"""

from __future__ import annotations

import ast
import inspect
import re
import textwrap
import types
from collections.abc import Set as AbstractSet
from dataclasses import MISSING, Field, dataclass, fields, is_dataclass
from pathlib import Path
from typing import Any, Literal, get_args, get_origin, get_type_hints

from srtctl.backends import MockerProtocol, SGLangProtocol, TRTLLMProtocol, VLLMProtocol
from srtctl.core.schema import ClusterConfig, SrtConfig

DEFAULT_OUTPUT = Path(__file__).resolve().parents[3] / "docs" / "schema-reference.md"

GENERATED_NOTICE = (
    "<!-- GENERATED FILE. Do not edit by hand. Regenerate with `srtctl schema-docs`; "
    "CI fails when this file is stale. -->"
)

# backend.type value -> dataclass. Order is the documentation order.
BACKEND_TYPES: tuple[tuple[str, type], ...] = (
    ("sglang", SGLangProtocol),
    ("trtllm", TRTLLMProtocol),
    ("vllm", VLLMProtocol),
    ("mocker", MockerProtocol),
)
_BACKEND_CLASSES: set[type] = {cls for _, cls in BACKEND_TYPES}


@dataclass(frozen=True)
class FieldDoc:
    """One row of a field table."""

    key: str
    type_label: str
    default: str
    description: str


# ---------------------------------------------------------------------------
# Type introspection
# ---------------------------------------------------------------------------


def _is_dataclass_type(obj: Any) -> bool:
    return isinstance(obj, type) and is_dataclass(obj)


def _dataclass_targets(annotation: Any) -> list[type]:
    """Dataclass types reachable from an annotation (through Annotated, unions, containers)."""
    if annotation is None:
        return []
    if _is_dataclass_type(annotation):
        return [annotation]
    origin = get_origin(annotation)
    if origin is None:
        return []
    found: list[type] = []
    for arg in get_args(annotation):
        for target in _dataclass_targets(arg):
            if target not in found:
                found.append(target)
    return found


def _type_label(annotation: Any) -> str:
    """Human-readable type, with dataclasses linked to their section."""
    if annotation is None:
        return "unknown"
    if annotation is type(None):
        return "None"
    if _is_dataclass_type(annotation):
        return f"[{annotation.__name__}](#{annotation.__name__.lower()})"
    origin = get_origin(annotation)
    if origin is None:
        return getattr(annotation, "__name__", str(annotation))
    if str(origin) == "typing.Annotated":
        return _type_label(get_args(annotation)[0])
    if origin is Literal:
        return "one of " + ", ".join(f"`{value!r}`" for value in get_args(annotation))
    if origin is types.UnionType or str(origin) == "typing.Union":
        return " \\| ".join(_type_label(arg) for arg in get_args(annotation))
    args = get_args(annotation)
    origin_name = getattr(origin, "__name__", str(origin).replace("typing.", ""))
    if not args:
        return origin_name
    if origin is tuple and len(args) == 2 and args[1] is Ellipsis:
        return f"tuple[{_type_label(args[0])}, ...]"
    return f"{origin_name}[{', '.join(_type_label(arg) for arg in args)}]"


def _yaml_key(item: Field) -> str | None:
    """The key a recipe author writes, or None when the field is not user-facing."""
    marshmallow_field = item.metadata.get("marshmallow_field")
    data_key = getattr(marshmallow_field, "data_key", None) if marshmallow_field is not None else None
    if data_key:
        return str(data_key)
    if item.name.startswith("_"):
        return None
    return item.name


def _default_label(item: Field) -> str:
    if item.default is not MISSING:
        return f"`{item.default!r}`"
    if item.default_factory is not MISSING:  # type: ignore[attr-defined]
        factory = item.default_factory  # type: ignore[attr-defined]
        if factory in (dict, list, tuple, set, frozenset):
            return f"`{factory()!r}`"
        name = getattr(factory, "__name__", type(factory).__name__)
        return f"`{name}()`"
    return "required"


# ---------------------------------------------------------------------------
# Descriptions from docstrings and source comments
# ---------------------------------------------------------------------------

_ATTRIBUTE_LINE = re.compile(r"^\s{1,8}([A-Za-z_]\w*)\s*(?:\([^)]*\))?:\s*(.*)$")


def _docstring_attributes(cls: type) -> dict[str, str]:
    """Parse a Google-style ``Attributes:`` block into {field: description}."""
    doc = inspect.getdoc(cls) or ""
    match = re.search(r"^Attributes:\s*$", doc, re.MULTILINE)
    if match is None:
        return {}
    descriptions: dict[str, str] = {}
    current: str | None = None
    for line in doc[match.end() :].splitlines():
        if not line.strip():
            continue
        indent = len(line) - len(line.lstrip())
        if indent == 0:
            break
        attribute = _ATTRIBUTE_LINE.match(line)
        if attribute and indent <= 4:
            current = attribute.group(1)
            descriptions[current] = attribute.group(2).strip()
        elif current:
            descriptions[current] = f"{descriptions[current]} {line.strip()}".strip()
    return descriptions


def _comment_descriptions(cls: type) -> dict[str, str]:
    """Comment block above each field, or the trailing comment on its line."""
    try:
        source = textwrap.dedent(inspect.getsource(cls))
    except (OSError, TypeError):
        return {}
    try:
        class_node = ast.parse(source).body[0]
    except (SyntaxError, IndexError):
        return {}
    if not isinstance(class_node, ast.ClassDef):
        return {}
    lines = source.splitlines()
    descriptions: dict[str, str] = {}
    for node in class_node.body:
        if not isinstance(node, ast.AnnAssign) or not isinstance(node.target, ast.Name):
            continue
        leading: list[str] = []
        index = node.lineno - 2
        while index >= 0 and lines[index].strip().startswith("#"):
            leading.insert(0, lines[index].strip().lstrip("#").strip())
            index -= 1
        text = " ".join(part for part in leading if part)
        if not text and node.end_lineno is not None and node.end_col_offset is not None:
            tail = lines[node.end_lineno - 1][node.end_col_offset :]
            if "#" in tail:
                text = tail.split("#", 1)[1].strip()
        if text:
            descriptions[node.target.id] = text
    return descriptions


def _descriptions(cls: type) -> dict[str, str]:
    merged = _comment_descriptions(cls)
    merged.update(_docstring_attributes(cls))
    return merged


def _class_summary(cls: type) -> str:
    doc = inspect.getdoc(cls) or ""
    first = doc.split("\n\n", 1)[0].strip()
    return " ".join(first.split())


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def _cell(text: str) -> str:
    return " ".join(text.split()).replace("|", "\\|")


def field_docs(cls: Any) -> list[FieldDoc]:
    """Field table rows for one dataclass, in declaration order."""
    hints = get_type_hints(cls, include_extras=True)
    descriptions = _descriptions(cls)
    rows: list[FieldDoc] = []
    for item in fields(cls):
        key = _yaml_key(item)
        if key is None:
            continue
        annotation = hints.get(item.name, item.type)
        rows.append(
            FieldDoc(
                key=key,
                type_label=_type_label(annotation),
                default=_default_label(item),
                description=descriptions.get(item.name, ""),
            )
        )
    return rows


def _render_table(cls: type) -> list[str]:
    out = ["| Key | Type | Default | Description |", "|---|---|---|---|"]
    for row in field_docs(cls):
        out.append(f"| `{row.key}` | {row.type_label} | {row.default} | {_cell(row.description)} |")
    return out


def _nested_types(cls: Any) -> list[type]:
    hints = get_type_hints(cls, include_extras=True)
    found: list[type] = []
    for item in fields(cls):
        if _yaml_key(item) is None:
            continue
        for target in _dataclass_targets(hints.get(item.name, item.type)):
            if target not in found:
                found.append(target)
    return found


def _walk(root: type, skip: AbstractSet[type]) -> list[type]:
    """Breadth-first list of dataclasses reachable from ``root`` (root excluded)."""
    order: list[type] = []
    queue = [root]
    seen = {root}
    while queue:
        current = queue.pop(0)
        for nested in _nested_types(current):
            if nested in seen or nested in skip:
                continue
            seen.add(nested)
            order.append(nested)
            queue.append(nested)
    return order


def _render_class_section(cls: type, level: int) -> list[str]:
    heading = "#" * level
    lines = [f"{heading} {cls.__name__}", ""]
    summary = _class_summary(cls)
    if summary:
        lines.extend([summary, ""])
    lines.extend(_render_table(cls))
    lines.append("")
    return lines


def render_schema_reference() -> str:
    """Render the full Markdown reference for recipes and the cluster config."""
    lines: list[str] = [
        "# Schema Reference",
        "",
        GENERATED_NOTICE,
        "",
        (
            "Field-level reference for recipe YAML (`SrtConfig`) and the cluster config "
            "`srtslurm.yaml` (`ClusterConfig`), generated from the dataclasses in "
            "`srtctl.core.schema` and `srtctl.backends`. Each table lists the YAML key, "
            "the type, the default (`required` when there is none), and a description "
            "taken from the class docstring or the comment on the field. Nested types "
            "link to their own table. For prose, examples, and semantics see "
            "[config-reference.md](config-reference.md)."
        ),
        "",
        "## Recipe",
        "",
        "Top-level keys of a recipe YAML.",
        "",
    ]
    lines.extend(_render_table(SrtConfig))
    lines.append("")

    nested = _walk(SrtConfig, skip=_BACKEND_CLASSES)
    if nested:
        lines.extend(["## Recipe sections", ""])
        for cls in nested:
            lines.extend(_render_class_section(cls, level=3))

    lines.extend(
        [
            "## Backend types",
            "",
            "`backend.type` selects one of the following; the remaining `backend` keys are that type's fields.",
            "",
        ]
    )
    backend_nested: list[type] = []
    for type_name, cls in BACKEND_TYPES:
        lines.extend([f"### {cls.__name__}", "", f"`backend.type: {type_name}`", ""])
        summary = _class_summary(cls)
        if summary:
            lines.extend([summary, ""])
        lines.extend(_render_table(cls))
        lines.append("")
        for extra in _walk(cls, skip=_BACKEND_CLASSES | set(nested)):
            if extra not in backend_nested:
                backend_nested.append(extra)
    for cls in backend_nested:
        lines.extend(_render_class_section(cls, level=3))

    lines.extend(
        [
            "## Cluster config",
            "",
            "Top-level keys of `srtslurm.yaml`. Recipes inherit these defaults and resolve aliases through them.",
            "",
        ]
    )
    lines.extend(_render_table(ClusterConfig))
    lines.append("")
    for cls in _walk(ClusterConfig, skip=_BACKEND_CLASSES | set(nested) | set(backend_nested)):
        lines.extend(_render_class_section(cls, level=3))

    return "\n".join(lines).rstrip() + "\n"


def write_schema_reference(output: Path = DEFAULT_OUTPUT) -> Path:
    """Write the rendered reference to ``output`` and return the path."""
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_schema_reference(), encoding="utf-8")
    return output


def schema_reference_is_current(output: Path = DEFAULT_OUTPUT) -> bool:
    """True when the checked-in file matches what the code renders."""
    if not output.exists():
        return False
    return output.read_text(encoding="utf-8") == render_schema_reference()
