# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Telemetry stage mixin for SweepOrchestrator."""

from __future__ import annotations

import logging
import os
import shlex
from collections.abc import Callable
from pathlib import Path
from typing import TYPE_CHECKING, Any

from srtctl.core.git_state import head_commit
from srtctl.core.power.contract import Reason
from srtctl.core.power.manifest import ExpectedWindow
from srtctl.core.power.session import PowerSessionSettings, PowerTelemetrySession
from srtctl.core.power.topology import build_expected_devices
from srtctl.core.processes import ManagedProcess, ProcessRegistry
from srtctl.core.schema import TelemetryExporterConfig
from srtctl.core.slurm import start_srun_process
from srtctl.core.telemetry import TACHOMETER_STORAGE_PARENT, generate_tachometer_config

if TYPE_CHECKING:
    from srtctl.core.runtime import RuntimeContext
    from srtctl.core.schema import SrtConfig, TachometerConfig
    from srtctl.core.topology import Process

logger = logging.getLogger(__name__)

# Power telemetry's template: 100ms NVML sampling is its purpose (dense power
# curves inside sa-bench measurement windows). Never used for tachometer.
DCGM_EXPORTER_COMMAND_TEMPLATE = "dcgm-exporter --collect-interval=100 --address :{port}"

# Lowest DCGM sampling interval measured at parity with no telemetry on GB300
# decode (A/F chain); 100ms measured ~2% ITL p50 overhead. Sampling faster than
# this is allowed but warned about at launch.
DCGM_PROVEN_SAFE_INTERVAL_MS = 1000

# process-exporter (ncabatoff) reads host /proc and publishes per-group CPU
# seconds by mode, thread count, per-THREAD-NAME CPU/count, context switches,
# RSS and open fds. Groups are defined by the YAML below, written into the run's
# log dir. ``-threads=true`` is what exposes
# namedprocess_namegroup_thread_{count,cpu_seconds_total}{threadname}: a runaway
# thread pool shows up as a step in thread_count and a CPU cluster on one
# threadname, which no application-level metric can express.
# ``-children=false``: a process is counted only by its own matcher, never
# folded into its parent's group (engine ranks stay separate from the launcher).
#
# Default launch is HOST-NATIVE (binary from `make setup`, config read at its
# host path); the container template applies only when a recipe gives a
# container_image (config then reached through the /logs mount).
PROCESS_EXPORTER_CONFIG_NAME = "process-exporter.yml"
PROCESS_EXPORTER_FLAGS = "-web.listen-address=:{port} -threads=true -children=false -recheck=false"
PROCESS_EXPORTER_COMMAND_TEMPLATE = (
    f"/bin/process-exporter -config.path /logs/{PROCESS_EXPORTER_CONFIG_NAME} {PROCESS_EXPORTER_FLAGS}"
)
PROCESS_EXPORTER_HOST_COMMAND_TEMPLATE = "{binary} -config.path {config_path} " + PROCESS_EXPORTER_FLAGS


def process_exporter_config_yaml() -> str:
    """Process groups for process-exporter, first match wins.

    ``cmdline`` regexps run against the full argv; ``comm`` is the 15-char kernel
    task name. The Dynamo frontend (``python3 -m dynamo.frontend``) gets its own
    group because it is the process every frontend CPU pathology lives in; the
    TRT-LLM/SGLang/vLLM worker handlers and their engine ranks share the
    ``dynamo.<backend>`` module name and are grouped per backend; the MPI
    launcher, the benchmark client and the infra daemons are named so their CPU
    is attributable rather than silently dropped. Unmatched processes are not
    exported (no catch-all): the per-thread breakdown of every process on a
    352-CPU node would be high-cardinality noise.
    """
    return """# Generated by srtctl (telemetry_stage.process_exporter_config_yaml). First match wins.
process_names:
  - name: frontend
    cmdline:
      - 'dynamo\\.frontend'
  - name: trtllm_llmapi_launch
    cmdline:
      - '^trtllm-llmapi-launch'
  - name: dynamo_trtllm
    cmdline:
      - 'dynamo\\.trtllm'
  - name: dynamo_sglang
    cmdline:
      - 'dynamo\\.sglang'
  - name: dynamo_vllm
    cmdline:
      - 'dynamo\\.vllm'
  - name: trtllm_serve
    cmdline:
      - 'trtllm-serve'
  - name: aiperf
    cmdline:
      - 'aiperf'
  - name: agentperf
    cmdline:
      - 'agentperf'
  - name: etcd
    comm:
      - etcd
  - name: nats
    comm:
      - nats-server
  - name: tachometer
    comm:
      - tachometer-scra
  - name: node_exporter
    comm:
      - node_exporter
  - name: dcgm_exporter
    comm:
      - dcgm-exporter
"""


def tachometer_dcgm_command_template(tachometer: TachometerConfig) -> str:
    """DCGM exporter command for the tachometer-owned launch.

    The exporter samples NVML exactly as often as tachometer scrapes it —
    ``observability.tachometer.collect_interval_ms`` rules both cadences, so
    every scrape sees a fresh value and no scrape sees a duplicate. An
    explicit ``dcgm_exporter.command`` in the recipe still wins (resolved in
    :func:`resolve_exporter_command`).
    """
    return f"dcgm-exporter --collect-interval={tachometer.collect_interval_ms} --address :{{port}}"


# Node-exporter collectors the tachometer launch enables. Beyond the original
# cpu/infiniband/meminfo trio, this adds the host scheduler-pressure family that
# distinguishes "the box is busy" from "real work is blocked waiting for a
# resource" -- the signal set the retired steady_probe.sh sampler carried and
# tachometer did not:
#   stat         -> node_procs_running / node_procs_blocked / node_context_switches_total
#   vmstat       -> node_vmstat_pgmajfault / node_vmstat_pgsteal_* (memory reclaim)
#   pressure     -> node_pressure_{cpu,memory,io}_* (PSI stall time)
#   meminfo_numa -> node_memory_numa_MemFree_bytes (per-NUMA-node free memory)
# All four are cheap procfs/sysfs reads (/proc/{stat,vmstat,pressure},
# /sys/devices/system/node/*/meminfo); unlike dense NVML sampling they carry no
# measured decode-latency cost. Scraper side: the vendored NodeExporterFilter
# passes the label-free stat/vmstat/pressure families through unchanged, keeps
# the NUMA `node` label of memory_numa_* as `numa_node=N`, and keeps `state` /
# `thread_state` for the processes collector (filters.rs; without those two
# rules the per-NUMA and per-state series collapsed into one). An explicit
# recipe ``node_exporter.command`` still wins (resolved in
# :func:`resolve_exporter_command`).
#   processes    -> node_processes_threads (host-wide thread total), node_processes_state
#                   (the cheapest "how many threads exist on this box" signal; #413)
NODE_EXPORTER_COLLECTORS = ("cpu", "infiniband", "meminfo", "stat", "vmstat", "pressure", "meminfo_numa", "processes")

# node_exporter's vmstat collector defaults to ``^(oom_kill|pgpg|pswp|pg.*fault).*``,
# which ships pgmajfault but NOT pgsteal_* (page-reclaim). steady_probe.sh carried
# both major faults and reclaim, so widen the field filter to add pgsteal. Verified
# against node-exporter v1.8.2: without this, node_vmstat_pgsteal_* is absent.
NODE_EXPORTER_VMSTAT_FIELDS = "^(oom_kill|pgpg|pswp|pgsteal|pg.*fault).*"


def tachometer_node_exporter_command_template() -> str:
    """node_exporter command for the tachometer-owned launch.

    Enables exactly :data:`NODE_EXPORTER_COLLECTORS` on top of
    ``--collector.disable-defaults`` so the scrape surface is explicit and
    stable regardless of the node_exporter image's built-in default set. The
    pressure collector is a no-op on kernels built without ``CONFIG_PSI``
    (e.g. hecate's ``6.17.0-nvidia-64k``, verified 2026-09-09) -- node_exporter
    simply omits the family, which downstream tolerates.
    """
    collectors = " ".join(f"--collector.{name}" for name in NODE_EXPORTER_COLLECTORS)
    return (
        f"/bin/node_exporter --web.listen-address=:{{port}} --collector.disable-defaults "
        f"{collectors} --collector.vmstat.fields={NODE_EXPORTER_VMSTAT_FIELDS}"
    )


def resolve_exporter_command(exporter_config: TelemetryExporterConfig, default_template: str) -> str:
    """The exact command string an exporter is launched with.

    Single source of truth so the manifest records what actually ran rather
    than the default, which would be false provenance under a custom command.
    """
    if exporter_config.command is None:
        return default_template.format(port=exporter_config.port)
    if "{port}" in exporter_config.command:
        return exporter_config.command.format(port=exporter_config.port)
    return exporter_config.command


def read_producer_commit() -> str | None:
    """The srt-slurm commit that produced the artifact, when available."""
    located = head_commit(Path(__file__).resolve())
    if located is None:
        return None
    root, commit = located
    # An installed copy nested inside an unrelated git tree must not stamp that repo's HEAD.
    if not (root / "src" / "srtctl").is_dir():
        return None
    return commit


class TelemetryStageMixin:
    """Mixin for telemetry startup stage."""

    config: SrtConfig
    runtime: RuntimeContext

    @property
    def backend_processes(self) -> list[Process]:
        """Backend worker processes."""
        raise NotImplementedError

    def _compute_frontend_topology(self) -> Any:
        """Frontend topology helper provided by FrontendStageMixin."""
        raise NotImplementedError

    def _start_exporter_container(
        self,
        *,
        exporter_config: TelemetryExporterConfig,
        name: str,
        nodelist: list[str],
        log_file: Path,
        default_command_template: str,
        use_bash_wrapper: bool = True,
        critical: bool = True,
        on_started: Callable[[ManagedProcess], None] | None = None,
    ) -> list[ManagedProcess]:
        """Start one exporter container across the requested nodes.

        Under SLURM heterogeneous jobs the nodelist may span both het
        components (prefill on group 0, decode on group 1). A single srun
        cannot target multiple het components, so we split the launch into
        one srun per group when needed.

        ``on_started`` runs immediately after each group's process is created,
        so a caller can take ownership before the next group is launched and a
        partial launch stays reachable by the outer cleanup path.
        """
        cmd_str = resolve_exporter_command(exporter_config, default_command_template)

        if self.runtime.nodes.het:
            groups: dict[int, list[str]] = {}
            for node in nodelist:
                g = self.runtime.nodes.het_group_for(node)
                if g is None:
                    raise RuntimeError(f"node {node!r} not in any het component")
                groups.setdefault(g, []).append(node)
            chunks = sorted(groups.items())
        else:
            chunks = [(-1, nodelist)]  # sentinel: no --het-group

        # Host-native exporters (``binary`` set) run straight on the node: no
        # container image, no mounts -- the command already carries host paths.
        host_native = bool(exporter_config.binary)
        managed: list[ManagedProcess] = []
        for group_id, nodes in chunks:
            het_group = group_id if group_id >= 0 else None
            chunk_log = log_file if len(chunks) == 1 else log_file.with_suffix(f".g{group_id}.out")
            proc = start_srun_process(
                command=shlex.split(cmd_str),
                nodes=len(nodes),
                ntasks=len(nodes),
                nodelist=nodes,
                output=str(chunk_log),
                container_image=None if host_native else exporter_config.container_image,
                container_mounts=None if host_native else self.runtime.container_mounts,
                srun_options=self.runtime.srun_options,
                het_group=het_group,
                use_bash_wrapper=use_bash_wrapper,
            )
            chunk_name = name if len(chunks) == 1 else f"{name}_g{group_id}"
            process = ManagedProcess(
                name=chunk_name,
                popen=proc,
                log_file=chunk_log,
                node=",".join(nodes),
                critical=critical,
            )
            if on_started is not None:
                on_started(process)
            managed.append(process)
        return managed

    def start_power_telemetry(self, registry: ProcessRegistry) -> PowerTelemetrySession | None:
        """Start DCGM power telemetry when it is enabled.

        Every provider-originated startup failure becomes session state once the
        session exists, so the orchestrator can still finalize artifacts and
        decide the exit code after the benchmark stage.
        """
        telemetry = self.config.telemetry
        if not telemetry.enabled:
            return None

        exporter_config = telemetry.dcgm_exporter
        if exporter_config is None:  # guaranteed by schema validation
            raise ValueError("telemetry.dcgm_exporter is required when telemetry is enabled")

        worker_nodes = sorted({process.node for process in self.backend_processes})
        power_dir = self.runtime.log_dir / telemetry.storage_subdir
        command = resolve_exporter_command(exporter_config, DCGM_EXPORTER_COMMAND_TEMPLATE)

        session = PowerTelemetrySession(
            settings=PowerSessionSettings(
                power_dir=power_dir,
                log_dir=self.runtime.log_dir,
                job_id=self.runtime.job_id,
                run_name=self.runtime.run_name,
                sample_interval_seconds=telemetry.collect_interval_ms / 1000.0,
                startup_timeout_seconds=telemetry.startup_timeout_seconds,
                request_timeout_seconds=telemetry.request_timeout_seconds,
                collector_join_timeout_seconds=telemetry.resolved_collector_join_timeout_seconds,
                required=telemetry.required,
                exporter_port=exporter_config.port,
                exporter_image=exporter_config.container_image,
                exporter_command=command,
                network_interface=self.runtime.network_interface,
                producer_git_commit=read_producer_commit(),
            ),
            expected_devices=build_expected_devices(self.backend_processes),
            expected_windows=[
                ExpectedWindow(benchmark_type=self.config.benchmark.type, concurrency=concurrency)
                for concurrency in self.config.benchmark.get_concurrency_list()
            ],
            nodes=worker_nodes,
        )
        # NOTE: stored before initialize() so a raise mid-startup still leaves a finalizable session.
        self._power_session = session
        self._power_telemetry_ready = False
        session.initialize()
        logger.info("Starting DCGM power telemetry (artifacts under %s)", power_dir)

        def own(process: ManagedProcess) -> None:
            registry.add_process(process)
            session.add_exporter(process)

        try:
            self._start_exporter_container(
                exporter_config=exporter_config,
                name="telemetry_dcgm_exporter",
                nodelist=worker_nodes,
                log_file=self.runtime.log_dir / "telemetry_dcgm_exporter.out",
                default_command_template=DCGM_EXPORTER_COMMAND_TEMPLATE,
                use_bash_wrapper=False,  # distroless exporter images have no shell
                critical=False,  # an exit is telemetry invalidity, not a sweep-critical failure
                on_started=own,
            )
        except Exception:
            logger.exception("DCGM exporter launch failed")
            session.record_reason(Reason.EXPORTER_LAUNCH_FAILED)
            return session

        if session.start_and_wait_for_readiness():
            self._power_telemetry_ready = True
        else:
            logger.warning("Power collector did not reach readiness within %.1fs", telemetry.startup_timeout_seconds)
        return session

    def power_telemetry_blocks_benchmark(self) -> bool:
        """Whether required-mode telemetry failed startup and must skip the workload.

        Running the formal benchmark without collection would burn the
        allocation producing a result no consumer may use. Best-effort mode
        keeps serving and leaves the gap auditable in the manifest.
        """
        session = getattr(self, "_power_session", None)
        if session is None:
            return False
        # NOTE: fail closed, so only proven readiness clears the gate.
        if getattr(self, "_power_telemetry_ready", False):
            return False
        return self.config.telemetry.required

    def finalize_power_telemetry(self, exit_code: int, *, interrupted: bool = False) -> int:
        """Finalize the power session and fold required-mode invalidity into the exit code.

        Runs before ``ProcessRegistry.cleanup()`` so the writer is closed and
        the manifest is durable while the exporters are still owned. Expected
        measurement invalidity follows required/best-effort policy. An
        unexpected finalizer exception is an operational failure: it is logged,
        forces a nonzero exit, and still allows process cleanup to continue.
        """
        session = getattr(self, "_power_session", None)
        if session is None:
            return exit_code

        reaped = getattr(self, "benchmark_child_reaped", None)
        allows_window_mutation = getattr(self, "benchmark_child_allows_window_mutation", None)
        if reaped is False:
            session.record_reason(Reason.BENCHMARK_CHILD_REAP_TIMEOUT)

        try:
            outcome = session.stop_and_finalize(
                interrupted=interrupted,
                allow_window_mutation=allows_window_mutation is True,
            )
        except Exception:
            logger.exception("Power telemetry finalization failed")
            return 1

        logger.info(
            "Power telemetry: status=%s publication_valid=%s reasons=%s",
            outcome.status,
            outcome.publication_valid,
            ",".join(outcome.reason_codes) or "none",
        )
        if outcome.exit_nonzero and exit_code == 0:
            logger.error("telemetry.required is set and power artifacts are not publishable")
            return 1
        return exit_code

    def _resolve_host_binary(self, binary: str) -> Path | None:
        """Resolve an exporter's host-native ``binary`` to an executable path, or None.

        Absolute paths are taken verbatim. Relative ones resolve against the
        srtctl checkout root (``SRTCTL_SOURCE_DIR`` from the sbatch script, else
        this file's repo root) -- where ``make setup`` installs host binaries.
        The path must exist on the compute nodes too; the checkout lives on the
        shared filesystem in every supported deployment, exactly like
        ``configs/nats-server`` and ``configs/etcd``.
        """
        p = Path(binary)
        candidates = [p] if p.is_absolute() else []
        if not p.is_absolute():
            source_dir = os.environ.get("SRTCTL_SOURCE_DIR")
            if source_dir:
                candidates.append(Path(source_dir) / p)
            candidates.append(Path(__file__).resolve().parents[4] / p)
        for candidate in candidates:
            if candidate.is_file() and os.access(candidate, os.X_OK):
                return candidate
        return None

    def _resolve_tachometer_binary(self, binary_path: str) -> str:
        """Resolve the default bare binary name against the checkout's bin/.

        An explicit ``binary_path`` is always respected verbatim. The default
        bare name used to rely on ``$PATH`` inside the srun step, while
        ``make setup`` installs the binary to ``<srtctl_root>/bin/`` — the
        same place ``validate_setup`` checks and the --bash lifecycle uses.
        """
        if binary_path != "tachometer-scraper":
            return binary_path
        candidates = []
        source_dir = os.environ.get("SRTCTL_SOURCE_DIR")
        if source_dir:
            candidates.append(Path(source_dir) / "bin" / binary_path)
        candidates.append(Path(__file__).resolve().parents[4] / "bin" / binary_path)
        for candidate in candidates:
            if candidate.is_file() and os.access(candidate, os.X_OK):
                return str(candidate)
        return binary_path

    def start_tachometer(self) -> list[ManagedProcess]:
        """Start Tachometer collection (follows ``observability.enabled``)."""
        observability = self.config.observability
        tachometer = observability.tachometer
        if not observability.tachometer_enabled:
            logger.info("Tachometer disabled")
            return []

        logger.info("Starting Tachometer")

        power_telemetry = self.config.telemetry
        dcgm_exporter = power_telemetry.dcgm_exporter if power_telemetry.enabled else tachometer.resolved_dcgm_exporter
        topology = self._compute_frontend_topology()
        config_path = self.runtime.log_dir / "tachometer_config.toml"
        config_path.write_text(
            generate_tachometer_config(
                processes=self.backend_processes,
                frontend_topology=topology,
                runtime=self.runtime,
                tachometer=tachometer,
                dcgm_exporter=dcgm_exporter,
                frontend_type=self.config.frontend.type,
            )
        )

        tachometer_dir = self.runtime.log_dir / tachometer.storage_subdir
        # Create only the PARENT of the storage path: tachometer-scraper aborts if the
        # storage leaf already exists. Same rule the --bash lifecycle already follows.
        (tachometer_dir / TACHOMETER_STORAGE_PARENT).mkdir(parents=True, exist_ok=True)
        local_dir = tachometer_dir / "local"
        local_dir.mkdir(parents=True, exist_ok=True)

        worker_nodes = sorted({process.node for process in self.backend_processes})
        processes: list[ManagedProcess] = []
        # Exporters run shell-less (distroless images have no bash — the same
        # rule the power path follows) and non-critical: telemetry sidecars
        # must never tear down the benchmark. Verified the hard way: a
        # bash-wrapped node-exporter (FROM scratch) died with execve() ENOENT
        # and, as a critical process, killed a 7-node run at startup.
        if not power_telemetry.enabled and tachometer.resolved_dcgm_exporter is not None:
            if tachometer.collect_interval_ms < DCGM_PROVEN_SAFE_INTERVAL_MS:
                logger.warning(
                    "observability.tachometer.collect_interval_ms=%d drives DCGM NVML "
                    "sampling below the measured-safe %dms; 100ms sampling cost ~2%% "
                    "decode ITL p50 on GB300. Proceeding as configured.",
                    tachometer.collect_interval_ms,
                    DCGM_PROVEN_SAFE_INTERVAL_MS,
                )
            processes.extend(
                self._start_exporter_container(
                    exporter_config=tachometer.resolved_dcgm_exporter,
                    name="tachometer_dcgm_exporter",
                    nodelist=worker_nodes,
                    log_file=self.runtime.log_dir / "tachometer_dcgm_exporter.out",
                    # NOT the power template (100ms): the tachometer exporter
                    # samples exactly as often as tachometer scrapes it, so one
                    # knob rules both cadences and every scrape is fresh.
                    default_command_template=tachometer_dcgm_command_template(tachometer),
                    use_bash_wrapper=False,
                    critical=False,
                )
            )
        if tachometer.resolved_node_exporter is not None:
            processes.extend(
                self._start_exporter_container(
                    exporter_config=tachometer.resolved_node_exporter,
                    name="tachometer_node_exporter",
                    nodelist=worker_nodes,
                    log_file=self.runtime.log_dir / "tachometer_node_exporter.out",
                    default_command_template=tachometer_node_exporter_command_template(),
                    use_bash_wrapper=False,
                    critical=False,
                )
            )
        process_exporter = tachometer.resolved_process_exporter
        if process_exporter is not None:
            # Every node with a backend rank OR a frontend replica: a dedicated /
            # head-placed frontend node hosts no backend process, and it is
            # exactly the node whose process telemetry matters most.
            exporter_nodes = sorted(set(worker_nodes) | set(topology.frontend_nodes))
            pe_config = self.runtime.log_dir / PROCESS_EXPORTER_CONFIG_NAME
            pe_config.write_text(process_exporter_config_yaml())
            template: str | None = PROCESS_EXPORTER_COMMAND_TEMPLATE
            if process_exporter.binary:
                binary = self._resolve_host_binary(process_exporter.binary)
                if binary is None:
                    logger.warning(
                        "process exporter: host binary %r not found under the srtctl root; run "
                        "`make setup ARCH=<compute_arch>` to install configs/process-exporter. "
                        "Skipping the process-exporter leg (per-process CPU/thread telemetry).",
                        process_exporter.binary,
                    )
                    template = None
                else:
                    template = PROCESS_EXPORTER_HOST_COMMAND_TEMPLATE.replace("{binary}", str(binary)).replace(
                        "{config_path}", str(pe_config)
                    )
            if template is not None:
                processes.extend(
                    self._start_exporter_container(
                        exporter_config=process_exporter,
                        name="tachometer_process_exporter",
                        nodelist=exporter_nodes,
                        log_file=self.runtime.log_dir / "tachometer_process_exporter.out",
                        default_command_template=template,
                        use_bash_wrapper=False,
                        critical=False,
                    )
                )

        cmd = [
            self._resolve_tachometer_binary(tachometer.binary_path),
            "--config",
            str(config_path),
            "--local-dir",
            str(local_dir),
        ]
        if tachometer.sync_interval_secs > 0:
            cmd.extend(["--sync-interval", str(tachometer.sync_interval_secs)])

        env_to_set: dict[str, str] = {}
        if tachometer.compaction_threads > 0:
            env_to_set["POLARS_MAX_THREADS"] = str(tachometer.compaction_threads)

        processes.append(
            ManagedProcess(
                name="tachometer",
                popen=start_srun_process(
                    command=cmd,
                    nodelist=[self.runtime.nodes.head],
                    output=str(self.runtime.log_dir / "tachometer.out"),
                    env_to_set=env_to_set,
                    srun_options=self.runtime.srun_options,
                    het_group=self.runtime.nodes.het_group_for(self.runtime.nodes.head),
                ),
                log_file=self.runtime.log_dir / "tachometer.out",
                node=self.runtime.nodes.head,
                # Best-effort by contract: telemetry must never kill a
                # benchmark. A dead scraper costs the capture, not the run;
                # the loss is visible in tachometer.out and the sweep log.
                critical=False,
            )
        )
        logger.info("Tachometer started with artifacts under %s", tachometer_dir)
        return processes
